package com.example.POC.service;

import java.util.ArrayList;
import java.util.List;
import org.json.JSONObject;
import org.springframework.stereotype.Service;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;

@Service
public class DataProvider {

  public String getFillingData() {
    return "{\"tiles\":[{\"campaignDetails\":{\"campaignId\":123,\"companyId\":456,\"groupId\":1,\"dataSource\":\"This is Description\",\"adId\":1233,\"subscriptionId\":4555,\"label\":\"this is label\",\"filters\":{\"entityDeptIds\":[],\"locationIds\":[],\"fareaIds\":[]}}},{\"campaignDetails\":{\"campaignId\":11112,\"companyId\":1321,\"groupId\":2,\"dataSource\":\"This is Description\",\"adId\":12343,\"subscriptionId\":44555,\"label\":\"this is label\",\"filters\":{\"entityDeptIds\":[],\"locationIds\":[],\"fareaIds\":[]}}},{\"campaignDetails\":{\"campaignId\":123,\"companyId\":456,\"groupId\":3,\"dataSource\":\"This is Description\",\"adId\":1233,\"subscriptionId\":4555,\"label\":\"this is label\",\"filters\":{\"entityDeptIds\":[],\"locationIds\":[],\"fareaIds\":[]}}},{\"campaignDetails\":{\"campaignId\":11112,\"companyId\":1321,\"groupId\":4,\"dataSource\":\"This is Description\",\"adId\":12343,\"subscriptionId\":44555,\"label\":\"this is label\",\"filters\":{\"entityDeptIds\":[],\"locationIds\":[],\"fareaIds\":[]}}},{\"campaignDetails\":{\"campaignId\":11112,\"companyId\":1321,\"groupId\":5,\"dataSource\":\"This is Description\",\"adId\":12343,\"subscriptionId\":44555,\"label\":\"this is label\",\"filters\":{\"entityDeptIds\":[],\"locationIds\":[],\"fareaIds\":[]}}},{\"campaignDetails\":{\"campaignId\":123,\"companyId\":456,\"groupId\":6,\"dataSource\":\"This is Description\",\"adId\":1233,\"subscriptionId\":4555,\"label\":\"this is label\",\"filters\":{\"entityDeptIds\":[],\"locationIds\":[],\"fareaIds\":[]}}},{\"campaignDetails\":{\"campaignId\":11112,\"companyId\":1321,\"groupId\":7,\"dataSource\":\"This is Description\",\"adId\":12343,\"subscriptionId\":44555,\"label\":\"this is label\",\"filters\":{\"entityDeptIds\":[],\"locationIds\":[],\"fareaIds\":[]}}},{\"campaignDetails\":{\"campaignId\":123,\"companyId\":456,\"groupId\":8,\"dataSource\":\"This is Description\",\"adId\":1233,\"subscriptionId\":4555,\"label\":\"this is label\",\"filters\":{\"entityDeptIds\":[],\"locationIds\":[],\"fareaIds\":[]}}},{\"campaignDetails\":{\"campaignId\":11112,\"companyId\":1321,\"groupId\":9,\"dataSource\":\"This is Description\",\"adId\":12343,\"subscriptionId\":44555,\"label\":\"this is label\",\"filters\":{\"entityDeptIds\":[],\"locationIds\":[],\"fareaIds\":[]}}},{\"campaignDetails\":{\"campaignId\":11112,\"companyId\":1321,\"groupId\":10,\"dataSource\":\"This is Description\",\"adId\":12343,\"subscriptionId\":44555,\"label\":\"this is label\",\"filters\":{\"entityDeptIds\":[],\"locationIds\":[],\"fareaIds\":[]}}}]}";
  }

  public JsonNode getAdArrayForJtwig() {
    String data = getFillingData();

    JsonNode cd = null;
    try {
      ObjectMapper mapper = new ObjectMapper();
      return mapper.readTree(data);

    } catch (Exception e) {
      e.printStackTrace();
    }

    return cd;
  }

  public JSONObject getAdArrayForThymeleaf() {
    String data = getFillingData();

    try {
      return new JSONObject(data);
    } catch (Exception e) {
      e.printStackTrace();
    }

    return new JSONObject();
  }


  public List<Recruiter_company_service> getRecruiterArray() {
    // Possible Groupids from 1 to 6
    List<Recruiter_company_service> recruiter_company_serviceArray = new ArrayList<>();
    Recruiter_company_service r1 = new Recruiter_company_service();
    Recruiter_company_service r2 = new Recruiter_company_service();

    r1.getSetOne();
    r2.getSetTwo();

    for (int i = 0; i < 12; i++) {
      recruiter_company_serviceArray.add(r1);
      recruiter_company_serviceArray.add(r2);
    }

    return recruiter_company_serviceArray;
  }

  public String getFreemrkerTemplate() {
    return "{\n" + "    \"bg_img_pos\": \"end\",\n" + "    \"subtitle\": \"\",\n"
        + "    \"title\": ${adCollection.tiles.get(0).campaignDetails.label},\n"
        + "    \"isMultipleSelectionInput\": false,\n" + "    \"footer_title\": \"\",\n"
        + "    \"bg_color\": <#if bg_color??>\"${bg_color}\"<#else>\"#FFFFFF\"</#if>,\n"
        + "    \"tuple_bg_color\": \"#FFFFFF\",\n" + "    \"widget_logo\": \"\",\n"
        + "    \"close_icon_avail\": false,\n"
        + "    \"desc_type\": \"brandingCollectionWidget\",\n" + "    \"bg_img\": \"\",\n"
        + "    \"maxOptionVisible\": 5,\n" + "    \"minOptionVisible\":3,\n"
        + "    \"options\": [ <#assign len=adCollection.tiles.size()-1><#list 0..len as i > <#assign tileArray=adCollection.tiles.get(i)>\n"
        + "        \"ubaEvent\":{\n" + "            \"name\":\"brandingView\",\n"
        + "            \"data\":{\n"
        + "                \"campaignId\": ${tileArray.campaignDetails.campaignId},\n"
        + "                \"companyId\": ${tileArray.campaignDetails.companyId},\n"
        + "                \"groupId\": ${tileArray.campaignDetails.groupId},\n"
        + "                \"adId\": ${tileArray.campaignDetails.adId},\n"
        + "                \"subscriptionId\": ${tileArray.campaignDetails.subscriptionId},\n"
        + "                \"type\": \"${ adType }\",\n" + "                \"filters\": {\n"
        + "                    \"fareaIds\": ${tileArray.campaignDetails.filters.fareaIds},\n"
        + "                    \"locationIds\": ${tileArray.campaignDetails.filters.locationIds},\n"
        + "                    \"domainIds\": ${tileArray.campaignDetails.filters.entityDeptIds}\n"
        + "                },\n" + "                \"label\": ${tileArray.campaignDetails.label}\n"
        + "            }\n" + "        },\n" + "        \"type\": \"brandingCollectionCard\",\n"
        + "        \"properties\": { <#assign groupId=tileArray.campaignDetails.groupId ?number , label=tileArray.campaignDetails.label>\n"
        + "            \"title\": \"${  recruiter_company_service_branding[groupId].groupName }\",\n"
        + "            \"tags\":  <#if recruiter_company_service_branding[groupId]??>[<#list recruiter_company_service_branding[groupId].customizedTags as tag >\"${tag}\",</#list>]<#else>[]</#if>,\n"
        + "            \"label\": ${label},\n" + "            \"description\": \"TBD\",\n"
        + "            \"isFollowing\": false,\n" + "            \"jobOpening\": 800,\n"
        + "            \"logo\": \"TBD\",\n"
        + "            \"id\": ${tileArray.campaignDetails.companyId},\n"
        + "            \"groupId\": ${tileArray.campaignDetails.groupId}\n" + "         },\n"
        + "         \"leftCTA\": {\n" + "            \"title\": \"Follow\",\n"
        + "            \"id\":  ${tileArray.campaignDetails.groupId},\n"
        + "            \"code\": \"Follow\",\n"
        + "            \"inAppTitle\":\"${  recruiter_company_service_branding[groupId].groupName }\",\n"
        + "            \"ubaEvent\": {\n" + "                \"name\":\"brandingClick\",\n"
        + "                \"data\":{\n"
        + "                    \"campaignId\": ${tileArray.campaignDetails.campaignId},\n"
        + "                    \"companyId\": ${tileArray.campaignDetails.companyId},\n"
        + "                    \"groupId\": ${tileArray.campaignDetails.groupId},\n"
        + "                    \"adId\": ${tileArray.campaignDetails.adId},\n"
        + "                    \"subscriptionId\": ${tileArray.campaignDetails.subscriptionId},\n"
        + "                    \"type\": \"${ adType }\",\n"
        + "                    \"filters\": {\n"
        + "                        \"fareaIds\": ${tileArray.campaignDetails.filters.fareaIds},\n"
        + "                        \"locationIds\": ${tileArray.campaignDetails.filters.locationIds},\n"
        + "                        \"domainIds\": ${tileArray.campaignDetails.filters.entityDeptIds}\n"
        + "                    },\n"
        + "                    \"label\": ${tileArray.campaignDetails.label},\n"
        + "                    \"CTA\" : \"Follow\"\n" + "                }\n" + "            }\n"
        + "        },\n" + "        \"rightCTA\": {\n" + "            \"title\": \"View jobs\",\n"
        + "            \"hitType\": \"inApp\",\n"
        + "            \"inAppTitle\":\"${  recruiter_company_service_branding[groupId].groupName }\",\n"
        + "            \"shouldRefreshImsOnCtaAction\": false,\"status\":true,\n"
        + "            \"fallbackUrl\": \"naukricompanypage://www.naukri.com/company/deloitte/jobs\",\n"
        + "            \"url\": \"https://www.naukri.com/${recruiter_company_service_group[groupId].overviewUrl}?tab=jobs\",\n"
        + "            \"ubaEvent\": {\n" + "                \"name\":\"brandingClick\",\n"
        + "                \"data\":{\n"
        + "                    \"campaignId\": ${tileArray.campaignDetails.campaignId},\n"
        + "                    \"companyId\": ${tileArray.campaignDetails.companyId},\n"
        + "                    \"groupId\": ${tileArray.campaignDetails.groupId},\n"
        + "                    \"adId\": ${tileArray.campaignDetails.adId},\n"
        + "                    \"subscriptionId\": ${tileArray.campaignDetails.subscriptionId},\n"
        + "                    \"type\": \"${ adType }\",\n"
        + "                    \"filters\": {\n"
        + "                        \"fareaIds\": ${tileArray.campaignDetails.filters.fareaIds},\n"
        + "                        \"locationIds\": ${tileArray.campaignDetails.filters.locationIds},\n"
        + "                        \"domainIds\": ${tileArray.campaignDetails.filters.entityDeptIds}\n"
        + "                    },\n"
        + "                    \"label\": ${tileArray.campaignDetails.label},\n"
        + "                    \"CTA\" : \"View jobs\"\n" + "                }\n"
        + "            }\n" + "        },\n" + "        \"click\": {\n"
        + "                \"shouldRefreshImsOnCtaAction\": false,\n"
        + "                \"inAppTitle\":\"${  recruiter_company_service_branding[groupId].groupName }\",\n"
        + "                \"hitType\": \"inApp\",\n"
        + "                \"fallbackUrl\": \"naukricompanypage://www.naukri.com/company/deloitte\",\n"
        + "                \"viewImagePath\": \"chevron\",\n"
        + "                \"url\": \"https://www.naukri.com/${recruiter_company_service_group[groupId].overviewUrl}\",\n"
        + "                    \"treatWholeWidget\" : true,\n" + "                \"ubaEvent\": {\n"
        + "                    \"name\":\"brandingClick\",\n" + "                    \"data\":{\n"
        + "                        \"campaignId\": ${tileArray.campaignDetails.campaignId},\n"
        + "                        \"companyId\": ${tileArray.campaignDetails.companyId},\n"
        + "                        \"groupId\": ${tileArray.campaignDetails.groupId},\n"
        + "                        \"adId\": ${tileArray.campaignDetails.adId},\n"
        + "                        \"subscriptionId\": ${tileArray.campaignDetails.subscriptionId},\n"
        + "                        \"type\": \"${ adType }\",\n"
        + "                        \"filters\": {\n"
        + "                            \"fareaIds\": ${tileArray.campaignDetails.filters.fareaIds},\n"
        + "                            \"locationIds\": ${tileArray.campaignDetails.filters.locationIds},\n"
        + "                            \"domainIds\": ${tileArray.campaignDetails.filters.entityDeptIds}\n"
        + "                        },\n"
        + "                        \"label\": ${tileArray.campaignDetails.label},\n"
        + "                        \"CTA\" : \"Tuple\"\n" + "                    }\n"
        + "                }\n" + "            }\n" + "         </#list> ],\n"
        + "    \"totalItemsCount\":${adCollection.tiles.size()},\n" + "    \"positiveCTA\": {\n"
        + "        \"title\": \"View all\",\n" + "        \"type\": \"1\",\n"
        + "        \"isBtn\": false,\n" + "        \"loginUrl\": \"\",\n"
        + "        \"treatWholeWidget\": false,\n" + "        \"inAppTitle\": \"\",\n"
        + "        \"shouldRefreshImsOnCtaAction\": true,\n"
        + "        \"url\": \"https://www.naukri.com/brandingWidgets?label=${ adCollection.tiles.get(0).campaignDetails.label }\",\n"
        + "        \"hitType\": \"inApp\",\n"
        + "        \"fallbackUrl\": \"https://www.naukri.com/brandingWidgets?title=${adCollection.tiles.get(0).campaignDetails.label}\",\n"
        + "        \"ubaEvent\": {\n" + "            \"name\":\"brandingClick\",\n"
        + "            data\":{\n" + "                \"CTA\" : \"View all\",\n"
        + "                \"type\": \"${adType }\",\n"
        + "                \"label\": \"${adCollection.tiles.get(0).campaignDetails.label}\",\n"
        + "                \"filters\": {\n"
        + "                    \"fareaIds\": ${adCollection.tiles.get(0).campaignDetails.filters.fareaIds},\n"
        + "                    \"locationIds\": ${adCollection.tiles.get(0).campaignDetails.filters.locationIds},\n"
        + "                    \"domainIds\": ${adCollection.tiles.get(0).campaignDetails.filters.entityDeptIds}\n"
        + "                },\n" + "            }\n" + "        }\n" + "    }\n" + "}";
  }

  public String getJtwigTemplate() {
    return "{\n" + "    \"bg_img_pos\": \"end\",\n" + "    \"subtitle\": \"\",\n"
        + "    \"title\": \"{{adCollection.tiles[0].campaignDetails.label}}\",\n"
        + "    \"isMultipleSelectionInput\": false,\n" + "    \"footer_title\": \"\",\n"
        + "        {% if bg_color is null %}\n" + "    \"bg_color\": \"#FFFFFF\",\n"
        + "        {% else %}\n" + "    \"bg_color\":\"{{bg_color}}\",\n" + "        {% endif %}\n"
        + "    \"tuple_bg_color\": \"#FFFFFF\",\n" + "    \"widget_logo\": \"\",\n"
        + "    \"close_icon_avail\": false,\n"
        + "    \"desc_type\": \"brandingCollectionWidget\",\n" + "    \"bg_img\": \"\",\n"
        + "    \"maxOptionVisible\": 5,\n" + "    \"minOptionVisible\":3,\n"
        + "    \"options\": [\n" + "        {% set ctr=0 %}\n"
        + "        {% for ad in adCollection.tiles %}                    \n"
        + "        {% set ctr=ctr+1 %}\n"
        + "        {% if (loop.first==false) and (ctr>1) %},{% endif %}{\n"
        + "            \"ubaEvent\":{\n" + "                \"name\":\"brandingView\",\n"
        + "                \"data\":{\n"
        + "                    \"campaignId\": {{ad.campaignDetails.campaignId}},\n"
        + "                    \"companyId\": {{ad.campaignDetails.companyId}},\n"
        + "                    \"groupId\": {{ad.campaignDetails.groupId}},\n"
        + "                    \"adId\": {{ad.campaignDetails.adId}},\n"
        + "                    \"subscriptionId\": {{ad.campaignDetails.subscriptionId}},\n"
        + "                    \"type\": \"{{ adType }}\",\n"
        + "                    \"filters\": {\n"
        + "                                {% if ad.campaignDetails.filters.fareaIds|length ==0 %}\n"
        + "                                    \"fareaIds\": [],\n"
        + "                                {% else %}\n"
        + "                                    \"fareaIds\": {{ad.campaignDetails.filters.fareaIds}},\n"
        + "                                {% endif %}\n"
        + "                                {% if ad.campaignDetails.filters.locationIds|length ==0 %}\n"
        + "                                    \"locationIds\": [],\n"
        + "                                {% else %}\n"
        + "                                    \"locationIds\": {{ad.campaignDetails.filters.locationIds}},\n"
        + "                                {% endif %}\n"
        + "                                {% if ad.campaignDetails.filters.entityDeptIds|length ==0 %}\n"
        + "                                    \"domainIds\": []\n"
        + "                                {% else %}\n"
        + "                                    \"domainIds\": {{ad.campaignDetails.filters.entityDeptIds}}\n"
        + "                                {% endif %}\n" + "                    },\n"
        + "                    \"label\": \"{{ad.campaignDetails.label}}\"\n"
        + "                }\n" + "            },\n"
        + "            \"type\": \"brandingCollectionCard\",\n" + "            \"properties\": {\n"
        + "                {% set groupId=ad.campaignDetails.groupId   %}  \n"
        + "                {% set label=ad.data.label %}   \n"
        + "                \"title\": \"{{  recruiter_company_service_branding[groupId].groupName }}\",\n"
        + "                {% if (recruiter_company_service_group[groupId] is empty) or (recruiter_company_service_branding[groupId].customizedTags is empty) %}   \n"
        + "                    \"tags\": [],\n" + "                {% else %}\n"
        + "                \"tags\":[\n"
        + "                    {% for companyTag in recruiter_company_service_branding[groupId].customizedTags %}\n"
        + "                \"{{companyTag}}\"{% if loop.last==false %},{% endif %}\n"
        + "                {% endfor %}\n" + "                ],\n"
        + "                {% endif %}\n" + "                \"label\": \"{{ad.data.label}}\",\n"
        + "                \"description\": \"TBD\",\n"
        + "                \"isFollowing\": false,\n" + "                \"jobOpening\": 800,\n"
        + "                \"logo\": \"recruiter_company_service_branding[groupId].groupLogoNew.mobile.v1\",\n"
        + "                \"id\": \"{{ad.campaignDetails.companyId}}\",\n"
        + "                \"groupId\": \"{{ad.campaignDetails.groupId}}\"\n" + "            },\n"
        + "            \"leftCTA\": {\n" + "                \"title\": \"Follow\",\n"
        + "                \"id\": \"{{ad.campaignDetails.groupId}}\",\n"
        + "                \"code\": \"Follow\",\n"
        + "                \"inAppTitle\":\"{{  recruiter_company_service_group[groupId].groupName }}\",\n"
        + "                \"ubaEvent\": {\n" + "                    \"name\":\"brandingClick\",\n"
        + "                    \"data\":{\n"
        + "                        \"campaignId\": {{ad.campaignDetails.campaignId}},\n"
        + "                        \"companyId\": {{ad.campaignDetails.companyId}},\n"
        + "                        \"groupId\": {{ad.campaignDetails.groupId}},\n"
        + "                        \"adId\": {{ad.campaignDetails.adId}},\n"
        + "                        \"subscriptionId\": {{ad.campaignDetails.subscriptionId}},\n"
        + "                        \"type\": \"{{ adType }}\",\n"
        + "                        \"filters\": {\n"
        + "                            {% if ad.campaignDetails.filters.fareaIds|length ==0 %}\n"
        + "                            \"fareaIds\": [],\n"
        + "                            {% else %}\n"
        + "                            \"fareaIds\": {{ad.campaignDetails.filters.fareaIds}},\n"
        + "                            {% endif %}\n"
        + "                            {% if ad.campaignDetails.filters.locationIds|length ==0 %}\n"
        + "                            \"locationIds\": [],\n"
        + "                            {% else %}\n"
        + "                            \"locationIds\": {{ad.campaignDetails.filters.locationIds}},\n"
        + "                            {% endif %}\n"
        + "                            {% if ad.campaignDetails.filters.entityDeptIds|length ==0 %}\n"
        + "                            \"domainIds\": []\n"
        + "                            {% else %}\n"
        + "                                \"domainIds\": {{ad.campaignDetails.filters.entityDeptIds}}\n"
        + "                            {% endif %}\n" + "                        },\n"
        + "                        \"label\": \"{{ad.campaignDetails.label}}\",\n"
        + "                        \"CTA\" : \"Follow\"\n" + "                    }\n"
        + "                }\n" + "            },\n" + "           \n"
        + "            \"rightCTA\": {\n" + "                \"title\": \"View jobs\",\n"
        + "                \"hitType\": \"inApp\",\n"
        + "                \"inAppTitle\":\"{{  recruiter_company_service_group[groupId].groupName }}\",\n"
        + "                \"shouldRefreshImsOnCtaAction\": false,\"status\":true,\n"
        + "                \"fallbackUrl\": \"naukricompanypage://www.naukri.com/company/deloitte/jobs\",\n"
        + "                \"url\": \"https://www.naukri.com/{{recruiter_company_service_group[groupId].overviewUrl}}?tab=jobs\",\n"
        + "                \"ubaEvent\": {\n" + "                    \"name\":\"brandingClick\",\n"
        + "                    \"data\":{\n"
        + "                        \"campaignId\": {{ad.campaignDetails.campaignId}},\n"
        + "                        \"companyId\": {{ad.campaignDetails.companyId}},\n"
        + "                        \"groupId\": {{ad.campaignDetails.groupId}},\n"
        + "                        \"adId\": {{ad.campaignDetails.adId}},\n"
        + "                        \"subscriptionId\": {{ad.campaignDetails.subscriptionId}},\n"
        + "                        \"type\": \"{{ adType }}\",\n"
        + "                        \"filters\": {\n"
        + "                                    {% if ad.campaignDetails.filters.fareaIds|length ==0 %}\n"
        + "                                    \"fareaIds\": [],\n"
        + "                                    {% else %}\n"
        + "                                    \"fareaIds\": {{ad.campaignDetails.filters.fareaIds}},\n"
        + "                                    {% endif %}\n"
        + "                                    {% if ad.campaignDetails.filters.locationIds|length ==0 %}\n"
        + "                                    \"locationIds\": [],\n"
        + "                                    {% else %}\n"
        + "                                    \"locationIds\": {{ad.campaignDetails.filters.locationIds}},\n"
        + "                                    {% endif %}\n"
        + "                                    {% if ad.campaignDetails.filters.entityDeptIds|length ==0 %}\n"
        + "                                    \"domainIds\": []\n"
        + "                                    {% else %}\n"
        + "                                        \"domainIds\": {{ad.campaignDetails.filters.entityDeptIds}}\n"
        + "                                    {% endif %}\n" + "                        },\n"
        + "                        \"label\": \"{{ad.campaignDetails.label}}\",\n"
        + "                        \"CTA\" : \"View jobs\"\n" + "                    }\n"
        + "                }\n" + "            },\n" + "            \n"
        + "            \"click\": {\n" + "                \"shouldRefreshImsOnCtaAction\": false,\n"
        + "                \"inAppTitle\":\"{{  recruiter_company_service_group[groupId].groupName }}\",\n"
        + "                \"hitType\": \"inApp\",\n"
        + "                \"fallbackUrl\": \"naukricompanypage://www.naukri.com/company/deloitte\",\n"
        + "                \"viewImagePath\": \"chevron\",\n"
        + "                \"url\": \"https://www.naukri.com/{{recruiter_company_service_group[groupId].overviewUrl}}\",\n"
        + "                    \"treatWholeWidget\" : true,\n" + "                \"ubaEvent\": {\n"
        + "                    \"name\":\"brandingClick\",\n" + "                    \"data\":{\n"
        + "                        \"campaignId\": {{ad.campaignDetails.campaignId}},\n"
        + "                        \"companyId\": {{ad.campaignDetails.companyId}},\n"
        + "                        \"groupId\": {{ad.campaignDetails.groupId}},\n"
        + "                        \"adId\": {{ad.campaignDetails.adId}},\n"
        + "                        \"subscriptionId\": {{ad.campaignDetails.subscriptionId}},\n"
        + "                        \"type\": \"{{ adType }}\",\n"
        + "                        \"filters\": {\n"
        + "                            {% if ad.campaignDetails.filters.fareaIds|length ==0 %}\n"
        + "                            \"fareaIds\": [],\n"
        + "                            {% else %}\n"
        + "                            \"fareaIds\": {{ad.campaignDetails.filters.fareaIds}},\n"
        + "                            {% endif %}\n"
        + "                            {% if ad.campaignDetails.filters.locationIds|length ==0 %}\n"
        + "                            \"locationIds\": [],\n"
        + "                            {% else %}\n"
        + "                            \"locationIds\": {{ad.campaignDetails.filters.locationIds}},\n"
        + "                            {% endif %}\n"
        + "                            {% if ad.campaignDetails.filters.entityDeptIds|length ==0 %}\n"
        + "                            \"domainIds\": []\n"
        + "                            {% else %}\n"
        + "                            \"domainIds\": {{ad.campaignDetails.filters.entityDeptIds}}\n"
        + "                            {% endif %}\n" + "                        },\n"
        + "                        \"label\": \"{{ad.campaignDetails.label}}\",\n"
        + "                        \"CTA\" : \"Tuple\"\n" + "                    }\n"
        + "                }\n" + "            }\n" + "        }\n" + "        {% endfor %}\n"
        + "    ],\n" + "    \"totalItemsCount\":{{ctr}},\n" + "    \"positiveCTA\": {\n"
        + "        \"title\": \"View all\",\n" + "        \"type\": \"1\",\n"
        + "        \"isBtn\": false,\n" + "        \"loginUrl\": \"\",\n"
        + "        \"treatWholeWidget\": false,\n" + "        \"inAppTitle\": \"\",\n"
        + "        \"shouldRefreshImsOnCtaAction\": true,\n"
        + "        \"url\": \"https://www.naukri.com/brandingWidgets?label={{ adCollection.tiles[0].campaignDetails.label }}\",\n"
        + "        \"hitType\": \"inApp\",\n"
        + "        \"fallbackUrl\": \"https://www.naukri.com/brandingWidgets?title={{adCollection.tiles[0].campaignDetails.label}}\",\n"
        + "        \"ubaEvent\": {\n" + "            \"name\":\"brandingClick\",\n"
        + "            \"data\":{\n" + "                \"CTA\" : \"View all\",\n"
        + "                \"type\": \"{{ adType }}\",\n"
        + "                \"label\": \"{{ad.campaignDetails.label}}\",\n"
        + "                \"filters\": {\n"
        + "                    {% if ad.campaignDetails.filters.fareaIds|length ==0 %}\n"
        + "                        \"fareaIds\": [],\n" + "                    {% else %}\n"
        + "                        \"fareaIds\": {{ad.campaignDetails.filters.fareaIds}},\n"
        + "                    {% endif %}\n"
        + "                    {% if ad.campaignDetails.filters.locationIds|length ==0 %}\n"
        + "                        \"locationIds\": [],\n" + "                    {% else %}\n"
        + "                        \"locationIds\": {{ad.campaignDetails.filters.locationIds}},\n"
        + "                    {% endif %}\n"
        + "                    {% if ad.campaignDetails.filters.entityDeptIds|length ==0 %}\n"
        + "                    \"domainIds\": []\n" + "                    {% else %}\n"
        + "                        \"domainIds\": {{ad.campaignDetails.filters.entityDeptIds}}\n"
        + "                    {% endif %}\n" + "                }\n" + "            }\n"
        + "        }\n" + "    }\n" + "}";
  }

  public String getThymeleafTemplate() {
    return "{\n" + "    \"bg_img_pos\": \"end\",\n" + "    \"subtitle\": \"\",\n"
        + "    \"title\": \"[[${title}]]\",\n" + "    \"isMultipleSelectionInput\": \"false\",\n"
        + "    \"footer_title\": \"\",\n"
        + "    \"bg_color\": \"[[${ #strings.isEmpty(bg_color) ? \"#FFFFFF\" :  bg_color }]]\",\n"
        + "    \"tuple_bg_color\": \"#FFFFFF\",\n" + "    \"widget_logo\": \"\",\n"
        + "    \"close_icon_avail\": false,\n"
        + "    \"desc_type\": \"brandingCollectionWidget\",\n" + "    \"bg_img\": \"\",\n"
        + "    \"maxOptionVisible\": 5,\n" + "    \"minOptionVisible\":3,\n"
        + "    \"options\": [  [# th:with=\"tileArray = ${ad.getJSONArray('tiles')} \" ] [# th:each=\" i: ${#numbers.sequence(0, tileArray.length() - 1)}\"]\n"
        + "        \"ubaEvent\":{\n" + "            \"name\":\"brandingView\",\n"
        + "            \"data\":{\n"
        + "                \"campaignId\": [(${tileArray.get(i).get(\"campaignDetails\").get(\"campaignId\")})],\n"
        + "                \"companyId\": [(${tileArray.get(i).get(\"campaignDetails\").get(\"companyId\")})],\n"
        + "                \"groupId\": [(${tileArray.get(i).get(\"campaignDetails\").get(\"groupId\")})],\n"
        + "                \"adId\": [(${tileArray.get(i).get(\"campaignDetails\").get(\"adId\")})],\n"
        + "                \"subscriptionId\": [(${tileArray.get(i).get(\"campaignDetails\").get(\"subscriptionId\")})],\n"
        + "                \"type\": \"[(${ adType })]\",\n" + "                \"filters\": {\n"
        + "                    \"fareaIds\":[(${tileArray.get(i).get(\"campaignDetails\").get(\"filters\").get(\"fareaIds\")})],\n"
        + "                    \"locationIds\":[(${tileArray.get(i).get(\"campaignDetails\").get(\"filters\").get(\"locationIds\")})],\n"
        + "                    \"domainIds\":[(${tileArray.get(i).get(\"campaignDetails\").get(\"filters\").get(\"entityDeptIds\")})]\n"
        + "                }\n"
        + "                \"label\": \"[(${tileArray.get(i).get(\"campaignDetails\").get(\"label\")})]\"\n"
        + "            }\n" + "        },\n" + "        \"type\": \"brandingCollectionCard\",\n"
        + "        \"properties\": {  [# th:with=\"groupId = ${tileArray.get(i).get('campaignDetails').get('groupId')} , label=${tileArray.get(i).get('campaignDetails').get('label')}\"] \n"
        + "            \"title\": \"[(${recruiter_company_service_branding[groupId-1].groupName})]\",\n"
        + "            \"tags\": [(${recruiter_company_service_branding[groupId-1].customizedTags})],\n"
        + "            \"label\": \"[(${tileArray.get(i).get(\"campaignDetails\").get(\"label\")})]\",\n"
        + "            \"description\":\"TBD\",\n" + "            \"isFollowing\": false,\n"
        + "            \"jobOpening\": 800,\n" + "            \"logo\": \"TBD\",\n"
        + "            \"id\": [(${tileArray.get(i).get(\"campaignDetails\").get(\"campaignId\")})],\n"
        + "            \"groupId\": [(${groupId})]],\n" + "        },\n"
        + "        \"rightCTA\": {\n" + "            \"title\": \"View jobs\",\n"
        + "            \"hitType\": \"inApp\",\n"
        + "            \"inAppTitle\":\"[(${recruiter_company_service_branding[groupId-1].groupName})]\",\n"
        + "            \"shouldRefreshImsOnCtaAction\": false,\"status\":true,\n"
        + "            \"fallbackUrl\": \"naukricompanypage://www.naukri.com/company/deloitte/jobs\",\n"
        + "            \"url\": \"https://www.naukri.com/[(${recruiter_company_service_group[groupId-1].overviewUrl})]?tab=jobs\",\n"
        + "            \"ubaEvent\": {\n" + "                \"name\":\"brandingClick\",\n"
        + "                \"data\":{\n"
        + "                    \"campaignId\": [(${tileArray.get(i).get(\"campaignDetails\").get(\"campaignId\")})],\n"
        + "                    \"companyId\": [(${tileArray.get(i).get(\"campaignDetails\").get(\"companyId\")})],\n"
        + "                    \"groupId\": [(${tileArray.get(i).get(\"campaignDetails\").get(\"groupId\")})],\n"
        + "                    \"adId\": [(${tileArray.get(i).get(\"campaignDetails\").get(\"adId\")})],\n"
        + "                    \"subscriptionId\": [(${tileArray.get(i).get(\"campaignDetails\").get(\"subscriptionId\")})],\n"
        + "                    \"type\": \"[(${ adType })]\",\n"
        + "                    \"filters\": {\n"
        + "                        \"fareaIds\":[(${tileArray.get(i).get(\"campaignDetails\").get(\"filters\").get(\"fareaIds\")})],\n"
        + "                        \"locationIds\":[(${tileArray.get(i).get(\"campaignDetails\").get(\"filters\").get(\"locationIds\")})],\n"
        + "                        \"domainIds\":[(${tileArray.get(i).get(\"campaignDetails\").get(\"filters\").get(\"entityDeptIds\")})]\n"
        + "                    }\n"
        + "                    \"label\": \"[(${tileArray.get(i).get(\"campaignDetails\").get(\"label\")})]\",\n"
        + "                    \"CTA\" : \"Follow\"\n" + "                }\n" + "            }\n"
        + "        },  \n" + "        \"leftCTA\": {\n" + "            \"title\": \"Follow\",\n"
        + "            \"id\": \"[(${tileArray.get(i).get(\"campaignDetails\").get(\"groupId\")})]\",\n"
        + "            \"code\": \"Follow\",\n"
        + "            \"inAppTitle\":\"[(${  recruiter_company_service_group[groupId-1].groupName })]\",\n"
        + "            \"ubaEvent\": {\n" + "                \"name\":\"brandingClick\",\n"
        + "                \"data\":{\n"
        + "                    \"campaignId\": [(${tileArray.get(i).get(\"campaignDetails\").get(\"campaignId\")})],\n"
        + "                    \"companyId\": [(${tileArray.get(i).get(\"campaignDetails\").get(\"companyId\")})],\n"
        + "                    \"groupId\": [(${tileArray.get(i).get(\"campaignDetails\").get(\"groupId\")})],\n"
        + "                    \"adId\": [(${tileArray.get(i).get(\"campaignDetails\").get(\"adId\")})],\n"
        + "                    \"subscriptionId\": [(${tileArray.get(i).get(\"campaignDetails\").get(\"subscriptionId\")})],\n"
        + "                    \"type\": \"[(${ adType })]\",\n"
        + "                    \"filters\": {\n"
        + "                        \"fareaIds\":[(${tileArray.get(i).get(\"campaignDetails\").get(\"filters\").get(\"fareaIds\")})],\n"
        + "                        \"locationIds\":[(${tileArray.get(i).get(\"campaignDetails\").get(\"filters\").get(\"locationIds\")})],\n"
        + "                        \"domainIds\":[(${tileArray.get(i).get(\"campaignDetails\").get(\"filters\").get(\"entityDeptIds\")})]\n"
        + "                    }\n"
        + "                    \"label\": \"[(${tileArray.get(i).get(\"campaignDetails\").get(\"label\")})]\",\n"
        + "                    \"CTA\" : \"Follow\"\n" + "                }\n" + "            }\n"
        + "        },\n" + "        \"click\": {\n"
        + "            \"shouldRefreshImsOnCtaAction\": false,\n"
        + "            \"inAppTitle\":\"[(${ recruiter_company_service_group[groupId-1].groupName })]\",\n"
        + "            \"hitType\": \"inApp\",\n"
        + "            \"fallbackUrl\": \"naukricompanypage://www.naukri.com/company/deloitte\",\n"
        + "            \"viewImagePath\": \"chevron\",\n"
        + "            \"url\": \"https://www.naukri.com/[(${recruiter_company_service_group[groupId-1].overviewUrl})]\",\n"
        + "                \"treatWholeWidget\" : true,\n" + "            \"ubaEvent\": {\n"
        + "                \"name\":\"brandingClick\",\n" + "                \"data\":{\n"
        + "                    \"campaignId\": [(${tileArray.get(i).get(\"campaignDetails\").get(\"campaignId\")})],\n"
        + "                    \"companyId\": [(${tileArray.get(i).get(\"campaignDetails\").get(\"companyId\")})],\n"
        + "                    \"groupId\": [(${tileArray.get(i).get(\"campaignDetails\").get(\"groupId\")})],\n"
        + "                    \"adId\": [(${tileArray.get(i).get(\"campaignDetails\").get(\"adId\")})],\n"
        + "                    \"subscriptionId\": [(${tileArray.get(i).get(\"campaignDetails\").get(\"subscriptionId\")})],\n"
        + "                    \"type\": \"[(${ adType })]\",\n"
        + "                    \"filters\": {\n"
        + "                        \"fareaIds\":[(${tileArray.get(i).get(\"campaignDetails\").get(\"filters\").get(\"fareaIds\")})],\n"
        + "                        \"locationIds\":[(${tileArray.get(i).get(\"campaignDetails\").get(\"filters\").get(\"locationIds\")})],\n"
        + "                        \"domainIds\":[(${tileArray.get(i).get(\"campaignDetails\").get(\"filters\").get(\"entityDeptIds\")})]\n"
        + "                    }\n"
        + "                    \"label\": \"[(${tileArray.get(i).get(\"campaignDetails\").get(\"label\")})]\",\n"
        + "                    \"CTA\" : \"Follow\"\n" + "                },\n"
        + "                \"label\": \"[(${tileArray.get(i).get(\"campaignDetails\").get(\"label\")})]\",\n"
        + "                \"CTA\" : \"Tuple\"\n" + "            }\n" + "        }\n"
        + "    ],[/][/][/]\n"
        + "    \"totalItemsCount\":[(${ad.getJSONArray('tiles').length()})],\n"
        + "    \"positiveCTA\": {\n" + "        \"title\": \"View all\",\n"
        + "        \"type\": \"1\",\n" + "        \"isBtn\": false,\n"
        + "        \"loginUrl\": \"\",\n" + "        \"treatWholeWidget\": false,\n"
        + "        \"inAppTitle\": \"\",\n" + "        \"shouldRefreshImsOnCtaAction\": true,\n"
        + "        \"url\": \"https://www.naukri.com/brandingWidgets?label=[(${ad.getJSONArray('tiles').get(0).get(\"campaignDetails\").get(\"label\") })]\",\n"
        + "        \"hitType\": \"inApp\",\n"
        + "        \"fallbackUrl\": \"https://www.naukri.com/brandingWidgets?title=[(${ad.getJSONArray('tiles').get(0).get(\"campaignDetails\").get(\"label\") })]\",\n"
        + "        \"ubaEvent\": {\n" + "            \"name\":\"brandingClick\",\n"
        + "            \"data\":{\n" + "                \"CTA\" : \"View all\",\n"
        + "                \"type\": \"[(${ adType })]\",\n"
        + "                \"label\": \"[(${ad.getJSONArray('tiles').get(0).get(\"campaignDetails\").get(\"label\")})]\",\n"
        + "                \"filters\": {\n"
        + "                    \"fareaIds\":[(${ad.getJSONArray('tiles').get(0).get(\"campaignDetails\").get(\"filters\").get(\"fareaIds\")})],\n"
        + "                    \"locationIds\":[(${ad.getJSONArray('tiles').get(0).get(\"campaignDetails\").get(\"filters\").get(\"locationIds\")})],\n"
        + "                    \"domainIds\":[(${ad.getJSONArray('tiles').get(0).get(\"campaignDetails\").get(\"filters\").get(\"entityDeptIds\")})]\n"
        + "                }\n" + "            }\n" + "        }\n" + "    }\n" + "}";
  }

  public String getPebbleTemplate() {
    return "{\n" + "    \"bg_img_pos\": \"end\",\n" + "    \"subtitle\": \"\",\n"
        + "    \"title\": \"{{adCollection.get('tiles')[0].get('campaignDetails').get('label')}}\",\n"
        + "    \"isMultipleSelectionInput\": false,\n" + "    \"footer_title\": \"\",\n"
        + "        {% if bg_color is null %}\n" + "    \"bg_color\": \"#FFFFFF\",\n"
        + "        {% else %}\n" + "    \"bg_color\":\"{{bg_color}}\",\n" + "        {% endif %}\n"
        + "    \"tuple_bg_color\": \"#FFFFFF\",\n" + "    \"widget_logo\": \"\",\n"
        + "    \"close_icon_avail\": false,\n"
        + "    \"desc_type\": \"brandingCollectionWidget\",\n" + "    \"bg_img\": \"\",\n"
        + "    \"maxOptionVisible\": 5,\n" + "    \"minOptionVisible\":3,\n"
        + "    \"options\": [\n" + "        {% set ctr=0 %}\n"
        + "        {% for ad in adCollection.get('tiles') %}                    \n"
        + "        {% set ctr=ctr+1 %}\n"
        + "        {% if (loop.first==false) and (ctr>1) %},{% endif %}{\n"
        + "        \"ubaEvent\":{\n" + "            \"name\":\"brandingView\",\n"
        + "            \"data\":{\n"
        + "                \"campaignId\": {{ad.get('campaignDetails').get('campaignId')}},  \n"
        + "                \"companyId\": {{ad.get('campaignDetails').get('companyId')}},\n"
        + "                \"groupId\": {{ad.get('campaignDetails').get('groupId')}},\n"
        + "                \"adId\": {{ad.get('campaignDetails').get('adId')}},\n"
        + "                \"subscriptionId\": {{ad.get('campaignDetails').get('subscriptionId')}},\n"
        + "                \"type\": \"{{ adType }}\",\n" + "                \"filters\": {\n"
        + "                    {% if ad.get('campaignDetails').get('filters').get('fareaIds')|length ==0 %}\n"
        + "                        \"fareaIds\": [],\n" + "                    {% else %}\n"
        + "                        \"fareaIds\": {{ad.get('campaignDetails').get('filters').get('fareaIds')}},\n"
        + "                    {% endif %}\n"
        + "                    {% if ad.get('campaignDetails').get('filters').get('locationIds')|length ==0 %}\n"
        + "                        \"locationIds\": [],\n" + "                    {% else %}\n"
        + "                        \"locationIds\": {{ad.get('campaignDetails').get('filters').get('locationIds')}},\n"
        + "                    {% endif %}\n"
        + "                    {% if ad.get('campaignDetails').get('filters').get('entityDeptIds')|length ==0 %}\n"
        + "                        \"domainIds\": []\n" + "                    {% else %}\n"
        + "                        \"domainIds\": {{ad.get('campaignDetails').get('filters').get('entityDeptIds')}}\n"
        + "                    {% endif %}\n" + "                },\n"
        + "                \"label\": \"{{ad.get('campaignDetails').get('label')}}\"\n"
        + "            }\n" + "        },\n" + "        \"type\": \"brandingCollectionCard\",\n"
        + "        \"properties\": {\n"
        + "            {% set groupId=ad.get('campaignDetails').get('groupId')  %}  \n"
        + "            {% set label=ad.get('campaignDetails').get('label') %}   \n"
        + "            \"title\": \"{{  recruiter_company_service_branding[groupId].groupName }}\",\n"
        + "            {% if (recruiter_company_service_group[groupId] is empty) or (recruiter_company_service_branding[groupId].customizedTags is empty) %}   \n"
        + "                \"tags\": [],\n" + "            {% else %}\n"
        + "            \"tags\":[\n"
        + "                {% for companyTag in recruiter_company_service_branding[groupId].customizedTags %}\n"
        + "            \"{{companyTag}}\"{% if loop.last==false %},{% endif %}\n"
        + "            {% endfor %}\n" + "            ],\n" + "            {% endif %}\n"
        + "            \"label\": \"{{ad.get('campaignDetails').get('label')}}\",\n"
        + "            \"description\": \"TBD\",\n" + "            \"isFollowing\": false,\n"
        + "            \"jobOpening\": 800,\n"
        + "            \"logo\": \"recruiter_company_service_branding[groupId].groupLogoNew.mobile.v1\",\n"
        + "            \"id\": {{ad.get('campaignDetails').get('companyId')}},\n"
        + "            \"groupId\":{{ad.get('campaignDetails').get('groupId')}}\n" + "        },\n"
        + "        \"leftCTA\": {\n" + "            \"title\": \"Follow\",\n"
        + "            \"id\": \"{{ad.get('campaignDetails').get('groupId')}}\",\n"
        + "            \"code\": \"Follow\",\n"
        + "            \"inAppTitle\":\"{{  recruiter_company_service_group[groupId].groupName }}\",\n"
        + "            \"ubaEvent\": {\n" + "                \"name\":\"brandingClick\",\n"
        + "                \"data\":{\n"
        + "                    \"campaignId\": {{ad.get('campaignDetails').get('campaignId')}},  \n"
        + "                    \"companyId\": {{ad.get('campaignDetails').get('companyId')}},\n"
        + "                    \"groupId\": {{ad.get('campaignDetails').get('groupId')}},\n"
        + "                    \"adId\": {{ad.get('campaignDetails').get('adId')}},\n"
        + "                    \"subscriptionId\": {{ad.get('campaignDetails').get('subscriptionId')}},\n"
        + "                    \"type\": \"{{ adType }}\",\n"
        + "                    \"filters\": {\n"
        + "                        {% if ad.get('campaignDetails').get('filters').get('fareaIds')|length ==0 %}\n"
        + "                            \"fareaIds\": [],\n" + "                        {% else %}\n"
        + "                            \"fareaIds\": {{ad.get('campaignDetails').get('filters').get('fareaIds')}},\n"
        + "                        {% endif %}\n"
        + "                        {% if ad.get('campaignDetails').get('filters').get('locationIds')|length ==0 %}\n"
        + "                            \"locationIds\": [],\n"
        + "                        {% else %}\n"
        + "                            \"locationIds\": {{ad.get('campaignDetails').get('filters').get('locationIds')}},\n"
        + "                        {% endif %}\n"
        + "                        {% if ad.get('campaignDetails').get('filters').get('entityDeptIds')|length ==0 %}\n"
        + "                            \"domainIds\": []\n" + "                        {% else %}\n"
        + "                            \"domainIds\": {{ad.get('campaignDetails').get('filters').get('entityDeptIds')}}\n"
        + "                        {% endif %}\n" + "                    },\n"
        + "                    \"label\": \"{{ad.get('campaignDetails').get('label')}}\"\n"
        + "                    \"CTA\" : \"Follow\"\n" + "                }\n" + "            }\n"
        + "        },  \n" + "        \"rightCTA\": {\n" + "            \"title\": \"View jobs\",\n"
        + "            \"hitType\": \"inApp\",\n"
        + "            \"inAppTitle\":\"{{  recruiter_company_service_group[groupId].groupName }}\",\n"
        + "            \"shouldRefreshImsOnCtaAction\": false,\"status\":true,\n"
        + "            \"fallbackUrl\": \"naukricompanypage://www.naukri.com/company/deloitte/jobs\",\n"
        + "            \"url\": \"https://www.naukri.com/{{recruiter_company_service_group[groupId].overviewUrl}}?tab=jobs\",\n"
        + "            \"ubaEvent\": {\n" + "                \"name\":\"brandingClick\",\n"
        + "                \"data\":{\n"
        + "                    \"campaignId\": {{ad.get('campaignDetails').get('campaignId')}},  \n"
        + "                    \"companyId\": {{ad.get('campaignDetails').get('companyId')}},\n"
        + "                    \"groupId\": {{ad.get('campaignDetails').get('groupId')}},\n"
        + "                    \"adId\": {{ad.get('campaignDetails').get('adId')}},\n"
        + "                    \"subscriptionId\": {{ad.get('campaignDetails').get('subscriptionId')}},\n"
        + "                    \"type\": \"{{ adType }}\",\n"
        + "                    \"filters\": {\n"
        + "                    {% if ad.get('campaignDetails').get('filters').get('fareaIds')|length ==0 %}\n"
        + "                        \"fareaIds\": [],\n" + "                    {% else %}\n"
        + "                        \"fareaIds\": {{ad.get('campaignDetails').get('filters').get('fareaIds')}},\n"
        + "                    {% endif %}\n"
        + "                    {% if ad.get('campaignDetails').get('filters').get('locationIds')|length ==0 %}\n"
        + "                        \"locationIds\": [],\n" + "                    {% else %}\n"
        + "                        \"locationIds\": {{ad.get('campaignDetails').get('filters').get('locationIds')}},\n"
        + "                    {% endif %}\n"
        + "                    {% if ad.get('campaignDetails').get('filters').get('entityDeptIds')|length ==0 %}\n"
        + "                        \"domainIds\": []\n" + "                    {% else %}\n"
        + "                        \"domainIds\": {{ad.get('campaignDetails').get('filters').get('entityDeptIds')}}\n"
        + "                    {% endif %}\n" + "                },\n"
        + "                \"label\": \"{{ad.get('campaignDetails').get('label')}}\"\n"
        + "                \"CTA\" : \"View jobs\"\n" + "                }\n" + "            }\n"
        + "        },\n" + "            \n" + "        \"click\": {\n"
        + "            \"shouldRefreshImsOnCtaAction\": false,\n"
        + "            \"inAppTitle\":\"{{  recruiter_company_service_group[groupId].groupName }}\",\n"
        + "            \"hitType\": \"inApp\",\n"
        + "            \"fallbackUrl\": \"naukricompanypage://www.naukri.com/company/deloitte\",\n"
        + "            \"viewImagePath\": \"chevron\",\n"
        + "            \"url\": \"https://www.naukri.com/{{recruiter_company_service_group[groupId].overviewUrl}}\",\n"
        + "                \"treatWholeWidget\" : true,\n" + "            \"ubaEvent\": {\n"
        + "                \"name\":\"brandingClick\",\n" + "                \"data\":{\n"
        + "                    \"campaignId\": {{ad.get('campaignDetails').get('campaignId')}},  \n"
        + "                    \"companyId\": {{ad.get('campaignDetails').get('companyId')}},\n"
        + "                    \"groupId\": {{ad.get('campaignDetails').get('groupId')}},\n"
        + "                    \"adId\": {{ad.get('campaignDetails').get('adId')}},\n"
        + "                    \"subscriptionId\": {{ad.get('campaignDetails').get('subscriptionId')}},\n"
        + "                    \"type\": \"{{ adType }}\",\n"
        + "                    \"filters\": {\n"
        + "                    {% if ad.get('campaignDetails').get('filters').get('fareaIds')|length ==0 %}\n"
        + "                        \"fareaIds\": [],\n" + "                    {% else %}\n"
        + "                        \"fareaIds\": {{ad.get('campaignDetails').get('filters').get('fareaIds')}},\n"
        + "                    {% endif %}\n"
        + "                    {% if ad.get('campaignDetails').get('filters').get('locationIds')|length ==0 %}\n"
        + "                        \"locationIds\": [],\n" + "                    {% else %}\n"
        + "                        \"locationIds\": {{ad.get('campaignDetails').get('filters').get('locationIds')}},\n"
        + "                    {% endif %}\n"
        + "                    {% if ad.get('campaignDetails').get('filters').get('entityDeptIds')|length ==0 %}\n"
        + "                        \"domainIds\": []\n" + "                    {% else %}\n"
        + "                        \"domainIds\": {{ad.get('campaignDetails').get('filters').get('entityDeptIds')}}\n"
        + "                    {% endif %}\n" + "                    },\n"
        + "                \"label\": \"{{ad.get('campaignDetails').get('label')}}\"\n"
        + "                \"CTA\" : \"Tuple\"\n" + "                }\n" + "            }\n"
        + "        }\n" + "    }{% endfor %}],\n" + "    \"totalItemsCount\":{{ctr}},\n"
        + "    \"positiveCTA\": {\n" + "        \"title\": \"View all\",\n"
        + "        \"type\": \"1\",\n" + "        \"isBtn\": false,\n"
        + "        \"loginUrl\": \"\",\n" + "        \"treatWholeWidget\": false,\n"
        + "        \"inAppTitle\": \"\",\n" + "        \"shouldRefreshImsOnCtaAction\": true,\n"
        + "        \"url\": \"https://www.naukri.com/brandingWidgets?label={{ adCollection.tiles[0].get('campaignDetails').get('label') }}\",\n"
        + "        \"hitType\": \"inApp\",\n"
        + "        \"fallbackUrl\": \"https://www.naukri.com/brandingWidgets?title={{adCollection.tiles[0].campaignDetails.label}}\",\n"
        + "        \"ubaEvent\": {\n" + "            \"name\":\"brandingClick\",\n"
        + "            \"data\":{\n" + "                \"CTA\" : \"View all\",\n"
        + "                \"type\": {{ adType }},\n"
        + "                \"label\": {{ad.get('campaignDetails').get('label')}},\n"
        + "                \"filters\": {\n"
        + "                    {% if ad.get('campaignDetails').get('filters').get('fareaIds')|length ==0 %}\n"
        + "                        \"fareaIds\": [],\n" + "                    {% else %}\n"
        + "                        \"fareaIds\": {{ad.get('campaignDetails').get('filters').get('fareaIds')}},\n"
        + "                    {% endif %}\n"
        + "                    {% if ad.get('campaignDetails').get('filters').get('locationIds')|length ==0 %}\n"
        + "                        \"locationIds\": [],\n" + "                    {% else %}\n"
        + "                        \"locationIds\": {{ad.get('campaignDetails').get('filters').get('locationIds')}},\n"
        + "                    {% endif %}\n"
        + "                    {% if ad.get('campaignDetails').get('filters').get('entityDeptIds')|length ==0 %}\n"
        + "                        \"domainIds\": []\n" + "                    {% else %}\n"
        + "                        \"domainIds\": {{ad.get('campaignDetails').get('filters').get('entityDeptIds')}}\n"
        + "                    {% endif %}\n" + "                },\n" + "            }\n"
        + "        }\n" + "    }\n" + "}";
  }
}
